### ISSUE TITLE
LibOpenRaid is breaking the Gamma cvar value

### ISSUE THREAD

**Issue by drnoonien** [Tercioo/Details-Damage-Meter#479]
**Game and Details! version**
WD10662 RELEASE 10.0.7

**Describe the bug**
Something related to `LibOpenRaid` is eating up other cvar values.

Repro:
- Set the Gamma cvar to some value
```
SET agentUID "wow"
SET Gamma "1.4"
SET lastCharacterIndex "1"
```
- Reload ui

Actual:
The gamma variable is appended to the end of the `LibOpenRaidTempCache` key, instead of being on its own line. See end of line.
```
SET agentUID "wow"
SET LibOpenRaidTempCache "^1^T^SgearInfo^S~}1~}T~}SRhod~}T~}SnoEnchants~}T~}N1~}N10~}t~}Silevel~}N414~}SequippedGear~}T~}N1~}T~}SgemSlots~}N0~}SitemLevel~}N418~}SgemId~}N0~}SitemName~}SHelmet~|`of~|`Reverent~|`Loyalty~}SenchantId~}N0~}SitemId~}N134513~}SitemLink~}S|cffa335ee|Hitem:134513::::::::70:65::35:9:8974:7977:6652:7936:8822:8820:9144:3297:8767|h[Helmet~|`of~|`Reverent~|`Loyalty]|r~}SslotId~}N1~}SitemQuality~}N4~}t~}N2~}T~}SgemSlots~}N3~}SitemLevel~}N418~}SgemId~}N192985~}SitemName~}SElemental~|`Lariat~}SenchantId~}N0~}SitemId~}N193001~}SitemLink~}S|cffa335ee|Hitem:193001::192985:192948:192948::::70:65::13:9:8836:8840:8902:8960:8783:8782:8802:8793:8846|h[Elemental~|`Lariat]|r~}SslotId~}N2~}SitemQuality~}N4~}t~}N3~}T~}SgemSlots~}N0~}SitemLevel~}N415~}SgemId~}N0~}SitemName~}SVirtuous~|`Silver~|`Pauldrons~}SenchantId~}N0~}SitemId~}N200419~}SitemLink~}S|cffa335ee|Hitem:200419::::::::70:65::16:5:6652:7977:8973:8826:1489|h[Virtuous~|`Silver~|`Pauldrons]|r~}SslotId~}N3~}SitemQuality~}N4~}t~}N4~}T~}SgemSlots~}N0~}SitemLevel~}N1~}SgemId~}N0~}SitemName~}SCommon~|`Gray~|`Shirt~}SenchantId~}N0~}SitemId~}N3428~}SitemLiSET Gamma "1.4"
SET lastCharacterIndex "1"
```

Expected:
The gamma variable isn't broken and and remains on its own line.
```
SET agentUID "wow"
SET LibOpenRaidTempCache "^1^T^SgearInfo^S~}1~}T~}SRhod~}T~}SnoEnchants~}T~}N1~}N10~}t~}Silevel~}N414~}SequippedGear~}T~}N1~}T~}SgemSlots~}N0~}SitemLevel~}N418~}SgemId~}N0~}SitemName~}SHelmet~|`of~|`Reverent~|`Loyalty~}SenchantId~}N0~}SitemId~}N134513~}SitemLink~}S|cffa335ee|Hitem:134513::::::::70:65::35:9:8974:7977:6652:7936:8822:8820:9144:3297:8767|h[Helmet~|`of~|`Reverent~|`Loyalty]|r~}SslotId~}N1~}SitemQuality~}N4~}t~}N2~}T~}SgemSlots~}N3~}SitemLevel~}N418~}SgemId~}N192985~}SitemName~}SElemental~|`Lariat~}SenchantId~}N0~}SitemId~}N193001~}SitemLink~}S|cffa335ee|Hitem:193001::192985:192948:192948::::70:65::13:9:8836:8840:8902:8960:8783:8782:8802:8793:8846|h[Elemental~|`Lariat]|r~}SslotId~}N2~}SitemQuality~}N4~}t~}N3~}T~}SgemSlots~}N0~}SitemLevel~}N415~}SgemId~}N0~}SitemName~}SVirtuous~|`Silver~|`Pauldrons~}SenchantId~}N0~}SitemId~}N200419~}SitemLink~}S|cffa335ee|Hitem:200419::::::::70:65::16:5:6652:7977:8973:8826:1489|h[Virtuous~|`Silver~|`Pauldrons]|r~}SslotId~}N3~}SitemQuality~}N4~}t~}N4~}T~}SgemSlots~}N0~}SitemLevel~}N1~}SgemId~}N0~}SitemName~}SCommon~|`Gray~|`Shirt~}SenchantId~}N0~}SitemId~}N3428~}SitemLi
SET Gamma "1.4"
SET lastCharacterIndex "1"
```

Here's the output of the debug var
```
SET LibOpenRaidTempCacheDebug "10:05:17| SaveData() called.
10:05:17| SaveData() units info serialized okay.
10:05:17| SaveData() cooldowns info serialized okay.
10:05:17| SaveData() gear info serialized okay.
10:05:17| CVars Saved on saveCahceOnCVar(), Size: 8397
"
```

**Comment by drnoonien** [comment]
This started happening on the 10.0.7/10.1.0 PTR and is now happening on retail after the patch.

**Comment by Flamanis** [comment]
Addons do not have direct filesystem access. We are using the blizzard SetCvar function to save as we're supposed to. It is their code that is not separating them into newlines.

**Comment by Dmeister406** [comment]
I am having the same issue with the cvar SET useMaxFPS "1"  being added to the end of it's output and thus being nullified upon relaunching the game. I only noticed it because my in game fps was no longer being capped.

**Comment by drnoonien** [comment]
Yeah from a little digging it seems to be related with the amount of stuff you're trying to shove into that poor cvar. Stuff start breaking at 1103 chars. Toy example here:

```
-- >=1103 breaks, <=1102 works
local payload = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

C_CVar.RegisterCVar("LibOpenRaidTempCache")
C_CVar.SetCVar("LibOpenRaidTempCache", payload)
C_UI.Reload()
```

A more localized fix for anyone that doesn't want to disable all of Details is commenting out these two lines in `LibOpenRaid.lua`
```
--~internal cache
--use a console variable to create a flash cache to keep data while the game reload
--this is not a long term database as saved variables are and it get clean up often

C_CVar.RegisterCVar(CONST_CVAR_TEMPCACHE) -- Comment out
C_CVar.RegisterCVar(CONST_CVAR_TEMPCACHE_DEBUG) -- Comment out
```
I'm sure it'll slow some things down, but I've been running without them for 2 days with no noticeable issues.

**Comment by Dmeister406** [comment]
@drnoonien Thanks for that LUA edit. It does indeed correct the issue.

Seems like allowing addons to cache info in the game config file is a weird decision....but Blizzard know best I guess.

**Comment by Flamanis** [comment]
We've been able to do this for a long while. With patch 10.0.7, it seems like blizzard has some max character count. Either there is enough item bloat to cause the length to extend that far, or there is a new limit.

**Comment by Flamanis** [comment]
Most recent version should avoid this issue for the time being until the issue is properly addressed by Blizzard.

**Comment by Kroxywuff** [comment]
The latest update didn't fix this issue. For me it's deleting the cvar line SET Sound_AmbienceVolume "0.20" and forcing the volume to default to 60% every time I open the game. It's also merging with SET KioskLobbyKickSeconds "30"

**Comment by Flamanis** [comment]
Latest alpha, apologies

**Comment by Chromos-Def** [comment]
Do we still need to resort to editing LibOpenRaid?

Sorry as I do not know how to check if it is still needed or not since this issue is still here.

**Comment by Tercioo** [comment]
> Do we still need to resort to editing LibOpenRaid?
> 
> Sorry as I do not know how to check if it is still needed or not since this issue is still here.

where did you got the information about this issue? I mean someone told you or you saw on a website maybe

**Comment by Chromos-Def** [comment]
> > Do we still need to resort to editing LibOpenRaid?
> > Sorry as I do not know how to check if it is still needed or not since this issue is still here.
> 
> where did you got the information about this issue? I mean someone told you or you saw on a website maybe

I noticed either my foreground or background FPS being uncapped. I looked in my Config.wtf fille and sure enough there was giant line of text on the same line as the cvar for FPS, so I investigated and came across this issue, but I cannot specifically remember how I found out about the issue......but if I recall correctly the line had LibOpenRaid in it so I googled that and looked at the issues here.

**Comment by Tercioo** [comment]
> 

so, it was a bug in the game which was fixed by blizzard late March, if it is still occurring, you may want to post on their forums.

**Comment by Chromos-Def** [comment]
Yes, the temporary fix posted by drnoonien worked for me like a charm and I had been applying it manually since then, but today I decided to try it without and so far so good.

I was merely posted to see if it was still occurring or not before I went ahead without editing LibOpenRaid as there were no more updates here on the issue.

I appreciate the replies.

**Comment by ItsMrMetaverse** [comment]
This seems to still be happening for me, at least the temporary fix is still working, and without it I have no voices.
